debugged messages output of  "exp_handler" recipes

diff --git a/templates/cpp/Makefile b/templates/cpp/Makefile
--- a/templates/cpp/Makefile
+++ b/templates/cpp/Makefile
@@ -12,14 +12,14 @@
 # sources extension (project language)
 SRCEXT				:= cpp
 # define the compiler to use (e.g: gcc, c++, ...)
-CCX					= auto
+CCX				= auto
 # define the compiler support version (e.g: 98, 99, 11, 14, 17, 2a, ...)
-COMPILER_SUPPORT	= auto
+COMPILER_SUPPORT		= auto
 # to compile big sized objects \
 (set to: 'true' if "too big file" exceptions occur, auto to handle it automatically or false to ignore it)
 BIGFILE				= auto
 # get general warnings (set to false to remove general warnings)
-GENERAL_WARNINGS    := true
+GENERAL_WARNINGS    		:= true
 # get larger amount of warnings (set to false to remove negligible warnings)
 USE_STRICT 			:= false
 
@@ -171,8 +171,8 @@ ifeq ($(OS),Windows_NT)
 	INCL_DIRS	:= $(INCLUDE_DIR_NAME)
 	LIB_DIRS	:= $(LIB_DIR_NAME)
 	FIXPATH 	= $1$(subst /,\,$1)
-	RM			= del /q /f
-	MD			:= @mkdir -p
+	RM		= del /q /f
+	MD		:= @mkdir -p
 else
 	TARGET		:= $(TARGET_NAME)
 	SRC_DIR		:= $(shell find $(SRC_DIR_NAME) -type d)
@@ -181,8 +181,8 @@ else
 	INCL_DIRS	:= $(shell find $(INCLUDE_DIR_NAME) -type d)
 	LIB_DIRS	:= $(shell find $(LIB_DIR_NAME) -type d)
 	FIXPATH 	= $1
-	RM 			= rm -f
-	MD			:= @mkdir -p
+	RM 		= rm -f
+	MD		:= @mkdir -p
 endif
 
 # define any directories containing header files other than /usr/include
@@ -202,9 +202,9 @@ DEPS		= $(OBJECTS:.o=.d)
 # deleting dependencies appended to the file from 'make depend'
 
 # finds all your objects that corrispond to your .cpp files, system agnostic version
-OBJECTS 		:= $(patsubst $(SRC_DIR)/%.$(SRCEXT), $(OBJ_DIR)/%.o, $(wildcard $(SRC_DIR)/*.$(SRCEXT)))
+OBJECTS 	:= $(patsubst $(SRC_DIR)/%.$(SRCEXT), $(OBJ_DIR)/%.o, $(wildcard $(SRC_DIR)/*.$(SRCEXT)))
 # defining target directory
-TARGET_OUTPUT	=	$(call FIXPATH,$(TARGET_DIR)/$(TARGET))
+TARGET_OUTPUT	= $(call FIXPATH,$(TARGET_DIR)/$(TARGET))
 
 
 
@@ -247,7 +247,7 @@ $(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
 
 
 #############################
-######### RECIPIES ##########
+########## RECIPES ##########
 #############################
 
 
@@ -257,10 +257,11 @@ exp_handler:
 		echo ;\
 		echo Attempt to handle "'Too big file'" exception by enabling the "'BIGFILE'" flag; \
 		echo ; \
-		$(MAKE) BIGFILE=true; \
-		echo ;\
-		echo Executing "'all'" complete by using "'BIGFILE'" flag!; \
-		echo ;\
+		if $(MAKE) BIGFILE=true; then \
+			echo Executing "'all'" complete by using "'BIGFILE'" flag!; \
+		else (echo; echo "'BIGFILE'" exceptions handler failed!; echo; exit 1); \
+		fi \
+	else (exit 1); \
 	fi
 
 #Make the Directories
